// scripts/generate-sw.js
// ─────────────────────────────────────────────────────────────────────────────
// Generates public/firebase-messaging-sw.js from environment variables.
// Run this before `next build` or `next dev` so the SW has real values.
// The generated file is gitignored — only this template script is committed.
// ─────────────────────────────────────────────────────────────────────────────

const fs   = require('fs');
const path = require('path');

// ── Load .env.local manually (no dotenv dependency needed) ───────────────────
// Vercel injects env vars natively; this fallback is only for local dev.
const envPath = path.resolve(__dirname, '../.env.local');
if (fs.existsSync(envPath)) {
  const lines = fs.readFileSync(envPath, 'utf8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const val = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, '');
    if (!process.env[key]) process.env[key] = val;
  }
}

const required = [
  'NEXT_PUBLIC_FIREBASE_API_KEY',
  'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN',
  'NEXT_PUBLIC_FIREBASE_PROJECT_ID',
  'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET',
  'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID',
  'NEXT_PUBLIC_FIREBASE_APP_ID',
];

const missing = required.filter((k) => !process.env[k]);
if (missing.length) {
  console.warn('[generate-sw] ⚠️  Missing env vars:', missing.join(', '));
  console.warn('[generate-sw] SW will not be generated. Set these in .env.local or Vercel dashboard.');
  process.exit(0); // soft fail — don't break the build
}

const content = `// firebase-messaging-sw.js  (AUTO-GENERATED — do not edit)
// Generated by scripts/generate-sw.js at build time.
// ─────────────────────────────────────────────────────────────────────────────
// Handles FCM background push messages — works even when screen is off and
// Chrome is fully closed.
//
// KEY DESIGN DECISIONS:
// 1. Firebase config is injected at build time from env vars (no hardcoded keys).
// 2. We use DATA-ONLY FCM messages (no "notification" field in the payload).
//    Android auto-handles messages with a "notification" field and may skip
//    the SW entirely. Data-only messages ALWAYS wake this SW.
// 3. A no-op fetch handler is included so Chrome treats this as a valid
//    PWA service worker (required for "Add to Home Screen" / install).
// ─────────────────────────────────────────────────────────────────────────────

importScripts('https://www.gstatic.com/firebasejs/10.12.4/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.12.4/firebase-messaging-compat.js');

// ── Firebase config (injected at build time from env vars) ───────────────────
const FIREBASE_CONFIG = {
  apiKey:            '${process.env.NEXT_PUBLIC_FIREBASE_API_KEY}',
  authDomain:        '${process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}',
  projectId:         '${process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID}',
  storageBucket:     '${process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}',
  messagingSenderId: '${process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}',
  appId:             '${process.env.NEXT_PUBLIC_FIREBASE_APP_ID}',
};

// ── Initialise Firebase immediately on SW load ───────────────────────────────
firebase.initializeApp(FIREBASE_CONFIG);
const messaging = firebase.messaging();

// onBackgroundMessage fires for data-only FCM messages when app is
// backgrounded, closed, or screen is off.
messaging.onBackgroundMessage((payload) => {
  console.log('[SW] Background FCM:', payload);
  _showNotification(payload.data || {});
});

// ── Raw push fallback (Web Push API — catches anything FCM might miss) ───────
self.addEventListener('push', (event) => {
  if (!event.data) return;
  try {
    const raw = event.data.json();
    // FCM wraps our data under raw.data for data-only messages
    const data = raw.data || raw;
    // Don't double-fire if onBackgroundMessage already handled it
    if (data._handled) return;
    event.waitUntil(_showNotification(data));
  } catch (_) {}
});

// ── Install: take control immediately ────────────────────────────────────────
self.addEventListener('install', (event) => {
  console.log('[SW] Installing — skipping waiting.');
  self.skipWaiting();
});

// ── Activate: claim all open tabs immediately ────────────────────────────────
self.addEventListener('activate', (event) => {
  console.log('[SW] Activating — claiming clients.');
  event.waitUntil(self.clients.claim());
});

// ── Fetch handler (no-op passthrough) ────────────────────────────────────────
// Chrome requires a fetch event listener for PWA installability.
// We just pass every request through to the network (no caching).
self.addEventListener('fetch', (event) => {
  // Let the browser handle it normally
  return;
});

// ── Show notification helper ─────────────────────────────────────────────────
function _showNotification(data) {
  const isIncomingCall  = data.type === 'incoming_call';
  const needsManualCall = data.type === 'call_outcome' && data.action === 'call_hotel';

  const title = data.title || (isIncomingCall ? '📞 Incoming AI Call' : 'TripTogether');
  const body  = data.body  || (isIncomingCall ? 'Tap to answer the call.' : 'Tap to view.');

  const openUrl = isIncomingCall
    ? '/call/receive'
    : (data.tripId ? \`/trip/\${data.tripId}/disruption\` : '/dashboard');

  // For needs_manual: open phone dialer directly on tap
  const actionUrl = needsManualCall && data.hotelPhone
    ? \`tel:\${data.hotelPhone.replace(/\\\\s+/g, '')}\`
    : openUrl;

  const options = {
    body,
    icon:  '/icon-12.png',
    badge: '/icon-12.png',
    tag:   isIncomingCall ? 'tt-incoming-call' : \`tt-notif-\${Date.now()}\`,
    data:  { openUrl, actionUrl, hotelPhone: data.hotelPhone || '', ...data },

    // Keep on screen until user acts
    requireInteraction: isIncomingCall || needsManualCall,

    // Vibration pattern (milliseconds on/off)
    vibrate: isIncomingCall
      ? [500, 200, 500, 200, 500, 200, 500, 200, 500, 200, 500]
      : [200, 100, 200],

    // Use system default notification sound
    silent: false,

    // Action buttons
    actions: isIncomingCall
      ? [
          { action: 'answer', title: '✅ Answer' },
          { action: 'dismiss', title: '✕ Dismiss' },
        ]
      : needsManualCall && data.hotelPhone
      ? [
          { action: 'call', title: \`📞 Call \${data.hotelName || 'Hotel'}\` },
          { action: 'view', title: 'View Details' },
        ]
      : [{ action: 'view', title: 'View' }],
  };

  return self.registration.showNotification(title, options);
}

// ── Notification click handler ───────────────────────────────────────────────
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const data   = event.notification.data || {};
  const action = event.action;

  if (action === 'dismiss') return;

  let targetUrl;
  if (action === 'call' || (!action && data.action === 'call_hotel' && data.hotelPhone)) {
    targetUrl = \`tel:\${(data.hotelPhone || '').replace(/\\\\s+/g, '')}\`;
  } else {
    targetUrl = data.openUrl || '/';
  }

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      if (targetUrl.startsWith('tel:')) {
        return clients.openWindow(targetUrl);
      }
      for (const client of windowClients) {
        if (client.url.includes(targetUrl) && 'focus' in client) {
          return client.focus();
        }
      }
      return clients.openWindow(targetUrl);
    })
  );
});
`;

const outPath = path.resolve(__dirname, '../public/firebase-messaging-sw.js');
fs.writeFileSync(outPath, content, 'utf8');
console.log('[generate-sw] ✅ Generated public/firebase-messaging-sw.js from env vars.');
